; Self Radio Fixed - Config
[Settings]
MusicDir=C:\users\steamuser\Documents\Rockstar Games\GTA V\User Music
Volume=0.55
Shuffle=0
ShowHud=1
AutoRadioOff=1
PauseOnFocus=1
ShowProgress=1
SpeedVolume=0
VehicleOnly=1
ThemeIndex=1
CurrentIndex=41
[Keys]
; Use System.Windows.Forms.Keys names
KeyMenu=J
KeyPause=O
KeyNext=K
KeyPrev=I
KeyVolUp=Oemplus
KeyVolDown=OemMinus
KeyShuffle=Oem1
KeySeekForward=OemPeriod
KeySeekBackward=Oemcomma
