; Self Radio Linux
[Settings]
MusicDir=/home/uzair/
Volume=0.55
Shuffle=0
ShowHud=1
AutoRadioOff=1
PauseOnFocus=1
ShowProgress=1
SpeedVolume=0
VehicleOnly=1
AutoPlayInVehicle=1
PositionalAudio=1
MaxAudibleDistance=60
ThemeIndex=1
CurrentIndex=0
RepeatMode=2
ShowVisualizer=1
VisualizerPosition=0
VisualizerAlwaysVisible=1
LowPassFilter=1
LastDirectory=/home/uzair/
LastTrackPath=

[Keys]
; Use System.Windows.Forms.Keys names
KeyMenu=J
KeyPause=O
KeyNext=K
KeyPrev=I
KeyVolUp=Oemplus
KeyVolDown=OemMinus
KeyShuffle=OemSemicolon
KeySeekForward=OemPeriod
KeySeekBackward=Oemcomma
KeyRepeat=B
KeyFavorite=N
KeyVisualizer=M
